<a href="https://colab.research.google.com/github/yuhan222/114-2-Programing-Language/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [67]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [68]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1lLcOA_CUkl6N0H6OiAUnQyBIUyRR45Q3CHSrPoK7vCE/edit?usp=sharing')

In [69]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('記帳本').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期    時間  分類   品項  金額 付款人  地點 支付方式 備註
0  2026-03-05  9:30  早餐  三明治  35   我  師大   現金  無
1  2026-03-05  9:30  早餐  三明治  35   我  師大   現金  無

In [70]:
import datetime

In [72]:

# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

sort = input("請輸入分類: ")
item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
person = input("請輸入付款人: ")
place = input("請輸入地點: ")
methods = input("請輸入支付方式: ")
remark = input("請輸入備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-04
請輸入時間 (格式：HH:MM): 12:00
請輸入分類: 午餐
請輸入品項: 便當
請輸入金額: 90
請輸入付款人: 我
請輸入地點: 師大
請輸入支付方式: 現金
請輸入備註: 無

In [73]:
date_str

'2026-03-04'

In [74]:
time_str

'12:00'

In [75]:
item

'便當'

In [76]:
amount

90.0

In [77]:
import pandas as pd

# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': sort,
    '品項': item,
    '金額': amount,
    '付款人': person,
    '地點': place,
    '支付方式': methods,
    '備註': remark
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [78]:
df

           日期     時間  分類   品項    金額 付款人  地點 支付方式 備註
0  2026-03-05   9:30  早餐  三明治    35   我  師大   現金  無
1  2026-03-05   9:30  早餐  三明治    35   我  師大   現金  無
2  2026-03-04  12:00  午餐   便當  90.0   我  師大   現金  無

In [79]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('記帳本')

In [80]:
data_to_write[-1]

['2026-03-04', '12:00', '午餐', '便當', 90.0, '我', '師大', '現金', '無']

In [81]:
# 第二步：將資料寫入工作表
row_to_write = data_to_write[-1]

# 將 NaN 轉換為 None，因為 gspread/JSON 不支援 NaN
cleaned_row = [None if pd.isna(x) else x for x in row_to_write]

worksheet.append_row(values=cleaned_row, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！